### ISSUE TITLE
这个dll不能在windows 11注入吗？

### ISSUE THREAD

**Issue by Furinazzz** [AneryCoft/Horion-China-Release#5]
今天更新了windows 11，发现注入不了
更新之前是windows 10 可以正常注入
现在只能注入官方版horion，不能注入china版
求助~~

**Comment by Furinazzz** [comment]
6 提完这个issus后 啥也没干 他自己好了 又可以注入了

**Comment by AneryCoft** [comment]
你使用了什么注入器？是否可以注入除了horion horioncn的其他客户端？

**Comment by Furinazzz** [comment]
> 你使用了什么注入器？是否可以注入除了horion horioncn的其他客户端？

目前只用过horion注入，这个问题已经解决了（我也不知道怎么解决的 刚发完issues就可以注入了
